[theme]
base="light"
primaryColor="#0078C8"       # 2degrees blue
backgroundColor="#ffffff"    # white background
secondaryBackgroundColor="#f5f5f5"  # light grey for cards
textColor="#000000"
font="sans serif"
